apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWXJRK3hXSVdmWU13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeU1ERXhNREExTVRCYUZ3MHpOVEV4TWpreE1ERXdNVEJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMwVHpKQWxuUVI1NSs5ajNpRHdnVUVaL1kxSEl6OGYzM0tFdGs0bzkxcHpBRVY2K0lpMGRRTERYeUYKd0c4cVRqR01SS25Za2NkbTkyUGIzUDNmOEIvVS9QY01Ua04rcDliSFNwQ3k3U3RvbTNGcnl6b1N3R0VjQy9iWgp5K1l6SFZUSmVZZ3FJVGkxKy9pcTBnOS8rYllpSy9hS2llbzE1K1lVZ0l1Um1VeUIrekhpKzBIbkh0V3kwU1hJCjY3aTdSKzJ5OGtRcEgxeFFFMzFuWTJnamhEaDNHWE1lbUZBRnpRZGNhcUkxNEsxWFNGZEoyTzZnWkZpUkJpR3YKdzkraVliTm91WE9JSUFqSGw2YmUxSWlXbGpmMm9PZExUd2xiVXU0dytoSHA4TFBvRnRVYXE0dzBDL1pvNDVubwo2Sk1pczNJNWt0TkdhSGRlc1pJcW9PUWd2SDZ6QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRa3Y5WkluMTNKZ2FQM1ZpYWVuRTYzSWEySDRUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQmZvUHdPS2pCVAo3ZHQvMW1UY0c5SXhiNjUzbUg0RDJwQ0pISWdEbDNzeFBlK2hodFI5VkNVMklML0o3Y3BtRy9qQ2lTM0RqbGV3CkRkRHNjZlRhcHRFR1c0bkk4ZEhVdE5YR1VDcjZsTWtLQ0wwK0M0RHJaWlpVWEJIbEZSWUpyME0vQ2V1c1AyT1EKTHgwdlYva1Arck1Rd1MvbVlHZGZUem1MUkFXaW00RUU2MGUrY0MzWktwTzJNVElCd0hUeTFlTFlIT3l0c04reQpnUGlMc0cva0F4NG9iM0h3dEdPckhlQjNSQ1VFeHM2S0puZFhNQVRXTWdKbitRNmRhVTl2bE9oTXV3ZEI4cTd1Ck9PaWxVNlBsZHpRaEtSdGlNMG01aGx0STdnUGUxL3h2b1VpSlc4MURtTm9CcEZrbU9adnpZWlF6UWpQTHJTRHUKeEs5bHhINStvQm9YCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://ADD456A8AD3284766DF33EA17F1A7780.gr7.eu-north-1.eks.amazonaws.com
  name: arn:aws:eks:eu-north-1:455542500449:cluster/demo-cluster
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRUhnUHd0U3Rad1l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1qZ3dOelUzTXpWYUZ3MHpOVEV4TWpZd09EQXlNelZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURBN212ZHBzTU41MlVmL3BFVjhUTW56WU1OUEdkTS9LQU54b2l0S1VjRkpUd0FnMzNJcy9iRnBZaVEKb0daR1k3MGl0ajl5TGtNaHVjUWdTb3NyaGNYOGo2UTNVZ0YrejlLNUVweWpqMUpBbTR6UnpSVE1EYUpnTHlLRgo0YlNpTHRiQnBrSjdWMHJzWVZHamVqbUdPRCs2bEwybmt5b2hUd3dtU1NJMlFnWHNUcUwyZWlhZ0lyNm1WOHFUClFUWENXZlYvazM2dEJGVjZlamNJU1pqQXhUWEFxbXNwZXVkN3VyNU9BbWgxT2JqWm5ETzJqT012OFA0bXNHeW4KMnprcGJ2cWlqSXFUd1BxZFpGbVpsK2N2Q29DMVdCZlZ1aHZqWDZGS1g0RDRyaXdHbVUwWi9JYkJYeXA1RnpxTgpNbjNyaUt4Uis0UmpFeGN1dGdLYkdvUERidGxCQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUUjcydHlWN2FrVjhtY1RqRUpCb0RKMEJvYVVEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ3NPVXBUczVsNgpjVUswcVhiSmROV2hQSmxKMExuYlBsM3h3NzNUTzNRbUxXYjNkb2s0bnpyMjFNZmpPb0FyNWorQ0RiL05XY25zCmIxL0Z6ZUZoZk43aWFZcHZTdmdiYzNaK28xYkxxN0U4elFmcUQweHJFQi9yT21TMnR6ZExkYzZ6VXJsZzRWdVkKL1RlaWFiV3JuUGx5OG5JamlvYS9COWpSNTJmOGFlUlBtdDZLbFVON2cwaUZWTXNMd0V5cEJMWCtqNGR2Z0daQwpUYUdlaTV2V3pwa0s1ZmlUSEtOR2RvY2czZmxOTDJSZHhBdFlTT1NFSTJ5ZFdiVitqSnJ1Z3ZaUS90RWFkUEppCldOL2Q2RkpONGN1RTZ5WGNLVHF5bExYV1BZcGJ6eGp4L3JPT3JFOWRyVnl5ZERjKzNjL0taUS9NSFU1eXZOQTkKcTUxdmF0dTFuMmY2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://6CD6B0488DB92E81C80592059355AFAC.sk1.eu-north-1.eks.amazonaws.com
  name: arn:aws:eks:eu-north-1:455542500449:cluster/demo-eks
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJY3R6elVPei9OZXd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1qZ3hNRFU1TVRCYUZ3MHpOVEV4TWpZeE1UQTBNVEJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURNZVFFd3hMRjlFTDlJRVNhZnpZUEtjMlBCK01QdnppclVtUDNETThxL1hzRnc4Uk5ZS3BWS0k2NTMKU2liZUpvK3ZmV3pNdTZ4OU56TGxtMXJxa0M1ekkvYmFzbW52VU1VeTZqaDFzeExMSFEyKzg3TTB3ZXd0TTVNWgoxdDVoSEM0Szdzb3AyK2xXTXBXaTJydmdnK2c3R2cwTi8yczFhU3VPMmVQL2h0UVpPK1J2cWxoNzEzZWVmb2N3CnZOTVlaQjJBTE1NYmwwTEdESHdrbFVEM0VNWUlmOHhDT0pqMnVtK0UrUDR3RERHdFBDZTluZmVubFJiYUxzZkQKWlNpUU9ocTNOQUU1cE80U0NydnFsclprQmF5N1FpL2RUZ05TV3ZUd1VrVFhKRzNjSkk1L2RpRkUvNWxDWnNMYwo4Zy9FTEQ4djZvSGZuRHUrL3NzMmJVRzlNdmdkQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSSm9hQXkwRmtteFhmMm9tWkJiUFNTaCtaVWpUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnR4L0lZTGVsVwphNkxFcEZVaURvSWJwYTVqNzZDWDdLZHB4OWxGODI5TkVXblhoYVVKY3hTclNDRXRXVFZMMjN1NTBFYVJYbEw4Cm5hcXVBeC9kSGlTVXZ6bVl6bS9TWDk0R0VhVDB1YTZYT28zRHc1RlNlTlZBamtNWTlrUitlUS9XdnZaUmF2ek4KY3pWM3JzQmVieWNzOTFncEJPNVkvcWdaQzJ1bTFNOVdFZHVzMEoyeUthRzRacXFqaE9scXhIL25lQTNoN21HUQo5Z3hBMFpYcXExNGhzN3RDOHd2YXBBK29HZFRFSE1QdmtQRnNJL1A5cU8rQmtnSkNyelEzRUZXV3Q3aXZIMUxqCkhQbVlqNFEwbXhOWDczcytWSWFic2kyMU9pZzlFSlRMS3lYMHFUazJPSWtlR1lOamJsS3NidnFuL1l2MVQ2Z3kKbGlHNHgzb2lDVDM2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://C3A282B6196B1532A159ACE864E5DAFA.yl4.eu-north-1.eks.amazonaws.com
  name: arn:aws:eks:eu-north-1:455542500449:cluster/python-eks
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQmFJb0RuVWRaOEV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeU1UZ3dORFV5TURsYUZ3MHpOVEV5TVRZd05EVTNNRGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURpc3BwT05QbnlCRzErc2FnSTN3QzJhOVFrMUxQTTI0Rlc5NW9JL28vODBEWjNMdjFBVmtEUnozVEoKUFVlUEZmZDF4bEJxdnFvQVRMWEhWSW9md25oYXZKVXFGUHlVRmp6aTF0V2o0WENMWnNxMWhSYWZCNk5aanFlVQpLdXFscXNNV0hNM2U2VDB5Y1A5QXRKdjhObUJ6QjNGaU9NNHczV2RubEtSLzhOZml0VElMZWVvdXpZY1hJT01TCnZ5cWcxZjQzSWRObmhpbzlMbGkzN25tell6bzVmeERmaW9NZDlQVFBaZmswVTg0NjJrdmpCUHhmMStLcWhtTEMKM3VZTjVOWHNKSnRCZkJWTmlFZHg2MTFvWWYxYkFiMGJCdzUrbmlyNllTUTc2dUx5d29sb0RiL2FaYjlkS1AzWQpCZUh2MHJzdXZnRG1YbklVM0draWVhOEthTVJ6QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUTittQ0RYZEIxVXRnYjVlS2xHMmhhRGlhNjd6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRRGdzZm5RbGtkQQo2NWdrQzhhSnZGdDIyc01RMnBxMHhrRk5YVXFrWVpnTStodzdIY1U5ejA0aGZjRldMbWRBSW9icWFyNUV0YkZlCm5naFE1TEYxSlZ1MkNnU240bjVXRjkvRzU2c1c3SjcvdjJ5VzZpS0pRQ2MxT1pBUmRsdFBac3dwK3pwRGs4NE4KSTJJMlRBd3Y1cGc5Mlg0dXRYODdGdGZsaXdBdzZ5TGNkRFltdjBZUStmN2pvalFvQjZkN2lNMC9XWCtkQzcrSgpSOEx2QnRma01pWkxNWkRtYWs5VHhNTXlWaFp4T0ZwQXplUGo5Q3RGQmlSaW5tN2ZOckVacjNGNFZWSnQvNHBiCnFpUmJuUHlEZEJoMnJnUWI1OTlKZi80dWVaZ0pLQ3pNNkFhY2FzS1dJc0JFaFlRTDV4VDlPbzE0Y25UY3RrSzcKcGpTT2lvVk5oOTJPCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://4BA3CEBE328656743030068842B75EDB.gr7.us-east-2.eks.amazonaws.com
  name: arn:aws:eks:us-east-2:455542500449:cluster/eks
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZE4yV1JaTlQzMFl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeU1UVXdOVEEwTURGYUZ3MHpOVEV5TVRNd05UQTVNREZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURCUDBzL0JmaDhTMHlSZm9LanZEY2VyTFVocVhnVmRKZ3Y4RzBXYjNsZFRaRGlXY0p4eURwQVRibzgKQTFoejBUeHNGQWhTWldCNWoyakVVMEY2NGx4TXRLL1pjNWtpMmRSam52NEdwZFZTNGpPb0t3THV5MDVJL3I0YwpYTlJmekZPR1d6V0NSVVMvNHArVi9KQk81VjE1cWZSQzlLZm9mWkVtWUZ0b2lRditzSEdoYXJMKzlWMDkzaUlGCko2cmZtYjBjNTc3OFBleXUyUWlHWGYwMDZMQm5hZWczYjl3c2dJMXJVcFFqd3I4bkxaVDBpNG1EUk1BMnBxbkwKREpYWlFCTzJLZlhlc1JXQTQzQXh5ZlBqeGZXWS9NU0tWdloxNXRiTDlkVmNsS1pPMGFYRHQzU1JId0ZOVkpwKwoyeVp0bGxCSHF0dnVOTWpKSG0zd3gyV2ExNTR0QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSVkJPRFV5V09YdklCY20wV1dPUE1LbTMxTkVUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQzB5TDlIVFdwVwp6K0p6Y3d3d1J0SS9zUlhDcW04SkdoS0JBOGJNTE16VjdFaXRJNGg2YldBUkhKS0JDbjN6VTRhVTVaTVZEZlVLCmdyRkpVcGk3Qm1oc201RWtDVEdtYXdjSjI2YmxubXcvWjVaS3I5bi9yZXRWd3dzdS9OL3oyVExhZGdZRW9KZVQKL1pPSFRyZEsvRFM0NXF3R0lkSGhiRjlJU0dQdCtINE9hcUQvV0tXVG90UEI4RFJFWitSMUROQmxkbEFCUTUzZwpLTkRSbjlLNk8xL2FhQUtCMjFLMXhvOGpDRkFlaGZST1NueUprN0Jya0pRNWNwQ1JTRUVLQ3FVclZrT0xQSTNSCm1EbGhVdzBCcG9UUmptQ0dvcE8vMEdwbmg3aTB1ZjVrcmtvZXhRbVJ2YkhsUkJwNUVGc0czcnA4U3RiUTlWcmMKRFdQcHlzeSswMm4rCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://44EE18457060B9E93AA28FBAC142118A.gr7.us-east-2.eks.amazonaws.com
  name: arn:aws:eks:us-east-2:455542500449:cluster/istio
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUmR5dVNqNHY5eTh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeU1USXdOVE0zTWpsYUZ3MHpOVEV5TVRBd05UUXlNamxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNpZWRJd3NGaHNKVzc5RHNxWmcvV1R2MGdEMWdZT3NWQTQ4VWFYRmVhcnorRkZHcWtzYWhlRXQyUTMKaVd0aFhjK0xOMmVtbHRYNTZaMUNscVVZeFV5OEFvNzhSa2luc0JlZXUxbCszZHdvREdFK0NRVUFpT3o5ZS8yVApmMUZsRHBma2VzOXRHVmRhdEwydmN1N2hKZ2ZiWitKNlFPVVIxQWJCd1VGdUc5V1I2Nm8wT3Y5MEhNcXU3YzNGCnZoREIxSmZPZE4wRittU2tjQk15RUhLQ01QM2l1YlUzeExHOFBhOSs3andzZGJzcUViRWl1RkJDdituczh2SjAKaWRpZGkwQVBJNWI3ZkFWMTl4RTBDeUpodngyWTY1d2I5aHJEcnhqREtwcnVvd1NXR2ZhVWpLOGhaQy9PaEkxdApHcC9CZzZJOXcwWExQdElYZ2EwSlY5SWIxbU1wQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSNU1XUlBaUGUzNC81TWlJNXlTUEtxOEZiQ0NqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0VMQkZZN2dCbwpBb2NlVzhGYjFvMzg5dHQ0Ri9oZzkrbTRZVlplVDFkVkFVSDBrUzlFUzRocTF1b0lOS1krMjRxZ29FRG9NbGppCnBQbmZvVDlKQ0o4NGVkV0FPTzRvNUR6cXBvVHhNL2FLQ0dDK1VCR0tDcEp5V1k1L05PRXQ4Z2ZTOE5YTHhjUEcKV2t0UHpsQWlKelNMWHYyVExNZ2czczJTeHRYbkN5cEVRZ0VoOGVpUjBWRi85S2hmTEIzdDR1WXRMZUhLVUNEYgpVbjYyWExVM1dLTTJlRzlPT1BwSklIWnN2ZkhnbGZJVHlVYURsNllmUjZsbWIzdEN3aWcxZDR3aS9KanQ5S3hOCjd4eHlJaWJreXZkQnpscUdseDBJdVY4RE1aYUpVdmxmQmN0WWtPY2dVa0hha1BidkRPMW5zOEN3WE9jc2xteFMKb3hyejh4SmZ0azJsCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://67F2C32D6A8FF3FC7CCC29053E75798B.gr7.us-east-2.eks.amazonaws.com
  name: arn:aws:eks:us-east-2:529134784986:cluster/EKS
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQ3JaQUxIU1pTQTR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeU1UUXdOek14TUROYUZ3MHpOVEV5TVRJd056TTJNRE5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURxbXJ3TkswSnBGWXpZWjdVSmxlM0d6THhHMGVwZm5NV3ZZTWY4V1JFalcxaFV2V0o3bDZ1V2NoeUoKc1FDazBTZ3hidU5HU2tvd1JOMkdxK1RJb2tvQi92cVVacDB6c0YzT1g4bVA5Tm9MTVh6NXRuRVlrZDc5ODNZVApLMklsVlRHNEt4MHVaaEkwemZzMGJkWTAyekhtRlowaFloNEdOYWJMblNkR2NKS2ZZeEttUk5FV2c3NW4yQlNUCjNhZHNuZkRDMWxBSktremhlelZCeDJDak5RUzFGaHFzamhMMUxhQmkyRDZUUGJacHhoUUVSbWcrK0ZheW4yMnoKcllsMkZCOTE0UnF5VnViYUozSTJaVGorb1JpZGJKVWNTQXdFSlkxKzhkWWUxWjBCOEJPS2ZpSnpRVXZRM3NqOApJMUErRENXZktNMXlqbUFKRGF3QkppZ3ZISDZiQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRWVBoa0xXdVJYdEdlSTMydjJXTEtBa3l1dGFqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2phTU1SVmhsMgpkWHFEZmVSYUMrdXlvUVlBVFMyKzRzRE9OdFFLczd4THAzNW1wQkdMd1RJdUZibFBRdWpqeUlqR21YSTY1aHczCk1odmtDbTJ0ekIvQkZtWkNCZnVxOXlVTGo1dStwSEljaFcvL1hDZ1JGK1RhMnlsNU90MFpRYmo1RVMzaGgwQ3cKK0x5aHNUVlRjaVZJMmlYTi9reGtJdnhuZVdvNVB5RWo5ZkJyejB0Q0YxcExwU05xbUtFVHFXWE00b3cxYjc4RgpPN0lhZlFSc3ExbmpwZHlhRSt2d2RQSXdERnk1NG1DclFqSzlxY2pPV3BYTnMxc0x6ZVcrLzlOaVgxMjJoMTM0CmJvQmo2c2hKL2R6SzlUdUh0bE9pa2NGZ05RWFRBT0pxWGVkRjVaNGs0a2pBUEpxVTc0LzIvZldZUzEycDNwYmEKZHhXZ1hQRi9tSVlHCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://6DF3A700A3080795199F7E97DB3C8791.sk1.us-west-2.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:455542500449:cluster/istio
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRWUNnRzN3U3RqTnNZUDdmRlY1WUZZVEFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlSbVkyRXpPVGN6WlMxaE16UTFMVFF3WldZdFlXUmxOaTFpWXpnM09HTXlZVEUyTW1FdwpJQmNOTWpVeE1qSTVNRFF5TmpNeVdoZ1BNakExTlRFeU1qSXdOVEkyTXpKYU1DOHhMVEFyQmdOVkJBTVRKR1pqCllUTTVOek5sTFdFek5EVXROREJsWmkxaFpHVTJMV0pqT0RjNFl6SmhNVFl5WVRDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQUtzVEhkb0twSnh2anBaa2dtSkY1OGxod1Zodk1JR0NEWnB3Mms4Sgpaa2pHaW1rUXBNUjY0OHRJUjZJKzlsWTNYbnhJMTZGRzZWa2VYbHZQVXBrejVLbW56Tkw2aHV1Y2V3OWVxRHQrCjV6RGc4eWNDWVZuZ1ozcU83eVo5SUhuOVlseVFBTzNLWDA4UUpoN2Fxa2lueDE0QzZ2RlRtcGttQmdiK202QWgKamlHN1hPVEh4b2hENG5SRmZ2WWw2RVc0Zzl6OXdXSHBzWFo4eDlIbk5sSjR5aGVyR2d5MGJXK2VUZ0MwdUFoYwptNmhZc3drK3cxdHFYSW1UbXc3ZFFlaXZQZGNkV0FYTEhQQ2pzRDlldmFEMFFxWVR0STVUNGUwYUxjWmY3cjRzCmJjSmlmZHBRTS8vNVZaTlN0TlU4NWt4VThuRDRteUZJUno4TnlGbm56UUlWdUtrMEh3SHJIcXF5ZjNzZTEyOXMKYytmZCtJdjZVdURNMTJTU2JrUVpXUkpvcjBKSUptQnE3RWFMMWFOd3FLVUZwVlNKNmJXS0VtMEhwZyt3R0dtTgpsUWdyMDJIOGxtNzFaclh2U0JiY3hHelhTUlpNdDhtQ2N5WUYvMzdmelNSSjF4a3QyelNrV0QyUEhIVFpqZTNLCjFwRlB1dVIrcTI4QVE5dEN1ZjFMNWV4YkFRSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVPWVZWODdBekF4MGNyamg5QTlrbUlTZVI1ejB3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFEZWpXMzVnUnZMbHp4QytMVk1NcXpaUjNybWxQMnlUclZ3WFhLd2tBMFpmClBQSmFMenk3dDFhcmk1VDFDSFpKMTlKMUw3cXlvSlFFa0tiYTNINE1IcnV3VjN5VTBYSkNwQXlTL2UwSzN0NkUKNlZFRWdML1JPTUcweXNsck9pcjZrN2JZQW5VaFEvU0FCTEhjdzNub0U5bFA5YitZZ2JTNmUrYXoxRTBSbTUvQwpjdTIxZmx5bVZNbDdad1V3UHd3ZXBCY0VyTDY4cVF5K3dWSU9Od0Q0T2hPU2ltdk0wSURtaUo4N00vdG9WWVRpCjRzcFY0T3BkRWNDbnVtL1ZkSnJEcGk4S0w4VlNyNnNpN1RnaFl3UkZQSnQwTnJNVXk2ZXZxNHBSbjRlTk9mVVgKblY5QnEzQzlCR1ZZcWFvTUZQWWxKV2JZZ3ZrMEZvUVBteWJDc2ZhUGVob2lpYjBiREJMeVExcDFnTkd3WS8wQQpnUkxHUVVLWUxXejQrUVVNdkRYRmMzQmtzMzJkalY1cjJXMlEwV2dmeXZwdVU2czE0eDJNdVA3NEVhalp6R0xlClplZUdpaGVzL3JSRHpnalM1dTJLU0xnT0w2QWVBczJ0ZjJKVDk0amt0dEhzZE5FVFFIcVg0VjFxV3A2U3MydU4KWWRidHUxcXh2V2hoa0pHbjYrOG5IQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://136.112.83.149
  name: gke_vahancheck-294903_us-central1-a_bullmq
- cluster:
    certificate-authority: C:\Users\rites\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Mon, 05 Jan 2026 12:08:37 IST
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    server: https://127.0.0.1:59356
  name: minikube
contexts:
- context:
    cluster: arn:aws:eks:eu-north-1:455542500449:cluster/demo-cluster
    user: arn:aws:eks:eu-north-1:455542500449:cluster/demo-cluster
  name: arn:aws:eks:eu-north-1:455542500449:cluster/demo-cluster
- context:
    cluster: arn:aws:eks:eu-north-1:455542500449:cluster/demo-eks
    user: arn:aws:eks:eu-north-1:455542500449:cluster/demo-eks
  name: arn:aws:eks:eu-north-1:455542500449:cluster/demo-eks
- context:
    cluster: arn:aws:eks:eu-north-1:455542500449:cluster/python-eks
    user: arn:aws:eks:eu-north-1:455542500449:cluster/python-eks
  name: arn:aws:eks:eu-north-1:455542500449:cluster/python-eks
- context:
    cluster: arn:aws:eks:us-east-2:455542500449:cluster/eks
    user: arn:aws:eks:us-east-2:455542500449:cluster/eks
  name: arn:aws:eks:us-east-2:455542500449:cluster/eks
- context:
    cluster: arn:aws:eks:us-east-2:455542500449:cluster/istio
    user: arn:aws:eks:us-east-2:455542500449:cluster/istio
  name: arn:aws:eks:us-east-2:455542500449:cluster/istio
- context:
    cluster: arn:aws:eks:us-east-2:529134784986:cluster/EKS
    user: arn:aws:eks:us-east-2:529134784986:cluster/EKS
  name: arn:aws:eks:us-east-2:529134784986:cluster/EKS
- context:
    cluster: arn:aws:eks:us-west-2:455542500449:cluster/istio
    user: arn:aws:eks:us-west-2:455542500449:cluster/istio
  name: arn:aws:eks:us-west-2:455542500449:cluster/istio
- context:
    cluster: gke_vahancheck-294903_us-central1-a_bullmq
    namespace: bullmq
    user: gke_vahancheck-294903_us-central1-a_bullmq
  name: gke_vahancheck-294903_us-central1-a_bullmq
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Mon, 05 Jan 2026 12:08:37 IST
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
users:
- name: arn:aws:eks:eu-north-1:455542500449:cluster/demo-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-north-1
      - eks
      - get-token
      - --cluster-name
      - demo-cluster
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: arn:aws:eks:eu-north-1:455542500449:cluster/demo-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-north-1
      - eks
      - get-token
      - --cluster-name
      - demo-eks
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: arn:aws:eks:eu-north-1:455542500449:cluster/python-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-north-1
      - eks
      - get-token
      - --cluster-name
      - python-eks
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: arn:aws:eks:us-east-2:455542500449:cluster/eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-2
      - eks
      - get-token
      - --cluster-name
      - eks
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: arn:aws:eks:us-east-2:455542500449:cluster/istio
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-2
      - eks
      - get-token
      - --cluster-name
      - istio
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: arn:aws:eks:us-east-2:529134784986:cluster/EKS
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-2
      - eks
      - get-token
      - --cluster-name
      - EKS
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: arn:aws:eks:us-west-2:455542500449:cluster/istio
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - istio
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: gke_vahancheck-294903_us-central1-a_bullmq
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin.exe
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
      interactiveMode: IfAvailable
      provideClusterInfo: true
- name: minikube
  user:
    client-certificate: C:\Users\rites\.minikube\profiles\minikube\client.crt
    client-key: C:\Users\rites\.minikube\profiles\minikube\client.key
